# Generated by Django 4.2.4 on 2023-08-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagenography', '0002_encrypted_items_delete_stagenography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encrypted_items',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/uploaded_images'),
        ),
    ]
